### ISSUE TITLE
Question: what format do the models need to be in for merging? 

### ISSUE THREAD

**Issue by vmajor** [arcee-ai/mergekit#11]
I must have missed something, but for the life of me I cannot find any information about the format of the models that mergekit expects.

Are they pytorch, safetensors? Can it use GGUF models because I see syntax that resembles huggingface-cli referencing TheBloke?

**Comment by cg123** [comment]
The models can be in either pytorch or safetensors format . Quantized models like GGUF or GTPQ will not work - it needs to be a full fp16 or fp32 model.

Hope this helps!

**Comment by vmajor** [comment]
Yes, thank you... I just forged bravely ahead and did it. Merging Orca 2 fails though and mergekit asks that I allow it to go ahead by `--allow-crimes` (lol), but it rejects this flag in legacy as unknown and I have no idea how to move into the life of crime when using the new version inside python.

**Comment by cg123** [comment]
Huh! What models are you trying to merge? That generally doesn't come up.

I can add `--allow-crimes` to `mergekit-legacy` in case that's what you actually want to do, though. : )

**Comment by vmajor** [comment]
Lol, that shows up when I try to merge neural-chat-7b-v3-1 with Orca-2-7b

Both are Llama 2 so I am curious why this error would show up at all. I was expecting errors when merging a PyTorch with a safetensors model, but no, that works.

I'd like to try it, yes.

**Comment by cg123** [comment]
Ah, that's what's going on - Orca-2-7b is Llama 2, but neural-chat-7b-v3-1 is actually Mistral based.

I've added the option in commit b7134dc0563a25a48d2499d1c4e75be198cd47d3. Unfortunately this particular merge almost certainly still won't work. Mistral uses GQA and has generally different dimensions from Llama-2 7b.

**Comment by vmajor** [comment]
wow, how did I miss that. Well you should know that I successfully merged neural-chat-7b-v3-1 (PyTorch) with Starling-LM-7B-alpha (safetensors),  and that worked out well, as now I see that both are Mistral based and individual format does not matter.

Fascinating stuff...

**Comment by shamanez** [comment]
@vmajor  Amazing. Could you please let me know what kind of merging method did you use? Is it pass_throguh?

**Comment by vmajor** [comment]
I used mergekit-legacy without any special arguments beyond weight and density, and the model size is a sum of sizes of the input models thus I believe it defaults to passthrough. 

I also merged Orca 13B with itself and got a really interesting boost in reasoning ability: https://huggingface.co/vmajor/Orca2-13B-selfmerge-26B

**Comment by shamanez** [comment]
Wow. That's impressive. So basically you stack two models on top of each other right?

**Comment by vmajor** [comment]
Yes. I wanted to see if model performance increases due to "acquiring new knowledge" or is it (also) more basic than that - increasing the number of layers. The conventional wisdom is that merging models adds new information.

In my Orca experiment, knowledge did not improve, but reasoning more than doubled, if the GSM8K benchmark is to be trusted.

**Comment by vmajor** [comment]
No. I did not perform any additional work on the merged model.

**Comment by shamanez** [comment]
Fascinating.

**Comment by LCorleone** [comment]
> wow, how did I miss that. Well you should know that I successfully merged neural-chat-7b-v3-1 (PyTorch) with Starling-LM-7B-alpha (safetensors), and that worked out well, as now I see that both are Mistral based and individual format does not matter.
> 
> Fascinating stuff...

hi, it seems that it can work well if two models are the same architecture? no matter the llama or mistral? @vmajor
