### ISSUE TITLE
KeyError: 'transformer.ln_f.weight'

### ISSUE THREAD

**Issue by andysingal** [arcee-ai/mergekit#132]
Notebook: https://colab.research.google.com/drive/1obulZ1ROXHjYLn6PPZJwRR6GzgQogxxb?usp=sharing&authuser=2#scrollTo=LGd7jlfCpNcg
<img width="449" alt="Screenshot 2024-01-24 at 3 54 45 PM" src="https://github.com/cg123/mergekit/assets/20493493/7ec2c9e0-29bf-40e9-8c86-dfcffd350e64">

<img width="906" alt="Screenshot 2024-01-24 at 3 54 15 PM" src="https://github.com/cg123/mergekit/assets/20493493/1b7677eb-7c09-4b11-a2bb-6ad157ca6413">

**Comment by cg123** [comment]
This error is coming up because the Phi-2 and Mistral architectures aren't compatible. There aren't yet any techniques included in mergekit that can merge completely different architectures. I'm looking into it though! This might be possible eventually.

**Comment by andysingal** [comment]
> This error is coming up because the Phi-2 and Mistral architectures aren't compatible. There aren't yet any techniques included in mergekit that can merge completely different architectures. I'm looking into it though! This might be possible eventually.

Thanks for your response, Love to understand what is the criteria for merging? . i am looking for slerp to eventually get DPO.

**Comment by cg123** [comment]
In general, if models are a) the same architecture and b) the same number of parameters then they should be able to be merged. So for example, pretty much any Mistral 7B model can be merged with any other Mistral 7B, but not a Llama 7B; and a Llama 7B model can be merged with pretty much any Llama 7B model, but not with a Llama 13B or 70B model.

There are some exceptions to this. Models that use different RoPE base frequencies, like CodeLlama vs regular Llama for example, won't work when merged. But for the most part you just need to care about the architecture and size.
