### ISSUE TITLE
Why must experts_number be a power of 2 if I want to use llama.cpp ?

### ISSUE THREAD

**Issue by ZhangEnmao** [arcee-ai/mergekit#144]
Hi, dear cg123. I have no knowledge about llama.cpp right now. Could you explain why experts_number nust be a power of 2 if I want to use llama.cpp ?  Thanks a lot, and I will learn something about llama.cpp .

**Comment by cg123** [comment]
I'm afraid I don't actually know too many details myself - I just know that the sorting algorithm they use for their top-K implementation depends on the input being a power-of-two length. There's no reason it wouldn't work with a different algorithm. That'd have to be implemented in llama.cpp, though. :) Hope that helps!

**Comment by ZhangEnmao** [comment]
I think I got the reason, man. I found this part in llama.cpp, thanks for you and your great project again !
![Uploading image.png…]()

**Comment by ZhangEnmao** [comment]
I think I got the reason, man. I found this part in llama.cpp, thanks for you and your great project again !
<img width="417" alt="image" src="https://github.com/arcee-ai/mergekit/assets/53638291/0c1f64b4-a0ed-46c1-9ab4-429e6a4cb9ca">
