### ISSUE TITLE
What is the difference between mergekit-moe and mergekit-yaml

### ISSUE THREAD

**Issue by Betai18n** [arcee-ai/mergekit#151]
I find that `mergekit-moe` and `mergekit-yaml` use different formats of yml, and the model files they generated are also different, but they all seem to be used for merging models, so I'm confused, what is the difference and function of these two commands?

**Comment by cg123** [comment]
`mergekit-yaml` is the script you should use for normal merges. It (generally) takes multiple models of the same size and combines them into a single model of that same size (whether by SLERP merge, or TIES, etc.)

`mergekit-moe` is for a certain very specific kind of merge, where you assemble a "mixture of experts" using the feedforward portions of separately-trained Llama or Mistral models. The output will always use the Mixtral architecture and will be larger than the input models, containing parts of all of them. 

Unless you specifically want a pseudo-MoE model assembled in that way `mergekit-yaml` is the script you want to use.

Hope this helps clear things up!
