### ISSUE TITLE
Have no tokenizer.model when using tokenizer_source = union

### ISSUE THREAD

**Issue by congson1293** [arcee-ai/mergekit#185]
I have merged two Mistral-base models that have different vocab sizes and I have simultaneously used both two configs: ```embed_slerp: true``` and ```tokenizer_source: union```. But in the output folder has no **tokenizer.model file**. Are there anyone know the way to fix the problem?

**Comment by cg123** [comment]
When merging tokenizers with `tokenizer_source: union` the output will always be a fast tokenizer, which gets saved as `tokenizer.json` instead of `tokenizer.model`. Is this file not present as well?

**Comment by congson1293** [comment]
> When merging tokenizers with `tokenizer_source: union` the output will always be a fast tokenizer, which gets saved as `tokenizer.json` instead of `tokenizer.model`. Is this file not present as well?

Yeah, it has the ```tokenizer.json``` file. Sorry I forgot can load a fast tokenizer using ```PreTrainedTokenizerFast```.
Thank u for your support.
