### ISSUE TITLE
Do mergekit support negative weight?

### ISSUE THREAD

**Issue by NeonBohdan** [arcee-ai/mergekit#213]
As [Task Arithmetic](https://arxiv.org/pdf/2212.04089.pdf) paper describes
`Users can negate task vectors to mitigate undesirable behaviors`

Can it be achieved by setting negative weight in mergekit config yaml?
How it interferes with `normalize` flag

**Comment by cg123** [comment]
Yes, this is supported. You need to set `normalize: false` for it to work.

I've found the behavior when using negative weights with transformer models a little unintuitive, but it's there!
