### ISSUE TITLE
FileNotFoundError for architecture json files

### ISSUE THREAD

**Issue by zsaladin** [arcee-ai/mergekit#216]
I'd like to use mergekit as a part of my package.
So I added it by `pip install`
But json files in `_data/architectures` are missing

## Reproduce

```sh
# in my virtual env
pip install git+https://github.com/arcee-ai/mergekit.git
mergekit-yaml
```

### Error
```
FileNotFoundError: [Errno 2] No such file or directory: '/my_workspace/.venv/lib/python3.9/site-packages/mergekit/_data/architectures/mistral.json'
```

### Missing files
```
ls -al .venv/lib/python3.9/site-packages/mergekit/_data/architectures 
total 0
drwxr-xr-x  4 daehee  staff  128 Mar 28 12:04 .
drwxr-xr-x  5 daehee  staff  160 Mar 28 12:04 ..
-rw-r--r--  1 daehee  staff    0 Mar 28 12:04 __init__.py
drwxr-xr-x  3 daehee  staff   96 Mar 28 12:04 __pycache__
```

You may need [package data](https://setuptools.pypa.io/en/latest/userguide/datafiles.html) property

**Comment by cg123** [comment]
Thanks for the report! I usually install as editable while testing so this was a blind spot.

This should work again now. Let me know if it gives you any other trouble!
