### ISSUE TITLE
Unsupported architecture, StableLmForCausalLM

### ISSUE THREAD

**Issue by Whylickspittle** [arcee-ai/mergekit#218]
File "/usr/local/bin/mergekit-yaml", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/workspace/why_code/mergekit/mergekit/options.py", line 76, in wrapper
    f(*args, **kwargs)
  File "/workspace/why_code/mergekit/mergekit/scripts/run_yaml.py", line 47, in main
    run_merge(
  File "/workspace/why_code/mergekit/mergekit/merge.py", line 45, in run_merge
    model_arch_info = [
  File "/workspace/why_code/mergekit/mergekit/merge.py", line 46, in <listcomp>
    get_architecture_info(m.config(trust_remote_code=options.trust_remote_code))
  File "/workspace/why_code/mergekit/mergekit/architecture.py", line 324, in get_architecture_info
    raise RuntimeError(f"Unsupported architecture {arch_name}")
RuntimeError: Unsupported architecture StableLmForCausalLM

Can you support this architecture , I appreciate your work

**Comment by Whylickspittle** [comment]
I learnt that the stablelm.json is based on the architecture StableLMEpochForCausalLM, rather than StableLmForCausalLM.
I wish you could upgrade the tools and support the architecture.

**Comment by cg123** [comment]
I've added a definition for StableLmForCausalLM in #220 - if you could give it a try and let me know if you run in to any issues that would be quite helpful!

**Comment by Whylickspittle** [comment]
> I've added a definition for StableLmForCausalLM in #220 - if you could give it a try and let me know if you run in to any issues that would be quite helpful!

Well, thanks for your update, the mergekits can support the StableLmForCausalLM.
Nonetheless, the new model from mergekit seems not as good as it should be, here is my parameters
`import yaml

MODEL_NAME = "Goat_Derrick03"
yaml_config = """
slices:
  - sources:
      - model: stabilityai/stablelm-2-zephyr-1_6b
        layer_range: [0, 24]
      - model: stabilityai/stablelm-2-zephyr-1_6b
        layer_range: [0, 24]
merge_method: slerp
base_model: stabilityai/stablelm-2-zephyr-1_6b
parameters:
  t:
    - filter: self_attn
      value: [0, 0.5, 0.3, 0.7, 1]
    - filter: mlp
      value: [1, 0.5, 0.7, 0.3, 0]
    - value: 0.5
dtype: float16
"""

# Save config as yaml file
with open('config.yaml', 'w', encoding="utf-8") as f:
    f.write(yaml_config)`

From my persperctive, the model that one model and its copy slerp should equal to itself.
it works, though the effect seems not well.
Thank you！

**Comment by Whylickspittle** [comment]
I am not sure that it is fine.
you can actually merge the model , though the models you get are idiots.
when I load the models, it shows it may need fine-tune,and the models can not speak like a normal LLM，here is my test examples:
`
conversation = [{"role": "user", "content": "Investigate the influence of advertising on media content."}]
input_ids =  tokenizer.apply_chat_template(
    conversation, truncation=True, return_tensors="pt",
    max_length=4096, add_generation_prompt=True,
).to('cuda')
output = model.generate(input_ids, generation_config=GenerationConfig(
    max_length=4096, do_sample=True, temperature=0.8,
    top_p=0.95, top_k=40, repetition_penalty=1.1,
    eos_token_id=tokenizer.eos_token_id, pad_token_id=tokenizer.eos_token_id
))
response = tokenizer.decode(output[0][len(input_ids[0]):], skip_special_tokens=True)
print(response)
`
![9](https://github.com/arcee-ai/mergekit/assets/49609811/90c85c16-ea03-4317-a4e6-5190b792e547)

![image](https://github.com/arcee-ai/mergekit/assets/49609811/643f85c4-90e2-4ba7-9f2b-d2fff0ab4280)
 @cg123   It didn't happened when I merged models that based on Gemma or Mistral.

**Comment by cg123** [comment]
Thanks for the report! That's definitely a bug. Could you try the branch for #225 and see if it behaves as you expect? I'm able to run the config you provided successfully with the fix, at least.

**Comment by Whylickspittle** [comment]
emmm...  I made several tries, it still looks terrible. I double-checked that the code I git clone is the branch--->stablelm2.
and I used the same test example and config.
here is my model_name {  Sumail/Goat_Derrick10 }
and here is test_result
![image](https://github.com/arcee-ai/mergekit/assets/49609811/b7ed585e-e717-43dd-bcba-648421cde860)

**Comment by cg123** [comment]
Oh, sorry, to be clear - the branch [fix-stablelm2](https://github.com/arcee-ai/mergekit/tree/fix-stablelm2) should work now. It looks like that's the branch from the previous PR.

**Comment by Whylickspittle** [comment]
> Oh, sorry, to be clear - the branch [fix-stablelm2](https://github.com/arcee-ai/mergekit/tree/fix-stablelm2) should work now. It looks like that's the branch from the previous PR.

OK, I got it.   I made two tests, the merged models performs like  I expect,
thank you for your kit and upgrades, MergeKing. Salute!
