### ISSUE TITLE
Wrong normalization for Stock of N>2 models

### ISSUE THREAD

**Issue by alexrame** [arcee-ai/mergekit#238]
Hi, thank you for the nice project. I believe there is an inconsistency when computing the optimal interpolating coefficient for Stock of N>2 models.
https://github.com/arcee-ai/mergekit/blob/ef7f5850f2658892b87f83d4955f817d398cd421/mergekit/merge_methods/model_stock.py#L81

While the formula is correct when merging 2 models (3 counting the base model), the formula from Eq.2 in https://arxiv.org/pdf/2403.19522.pdf implies that this line should be replaced by:

```
N = len(ws)
t = (N * cos_theta) / (1 + (N-1) * cos_theta)
```

**Comment by cg123** [comment]
You're absolutely right, thanks for pointing this out! I'll get a fix out soon.
