### ISSUE TITLE
pip version 21.3.1 but still fails with the error

### ISSUE THREAD

**Issue by wangyuchen333** [arcee-ai/mergekit#259]
```
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode:
(A "pyproject.toml" file was found, but editable mode currently requires a setuptools-based build.)
```
I am wondering if someone got this problem before and fixed it.

**Comment by wangyuchen333** [comment]
I upgraded my python version from 3.6 to 3.10, the maximum version of setuptool and pip don't work when it's 3.6 I guess

**Comment by w601sxs** [comment]
python 310 and upgraded pip, still doesn't install. same error as above
