### ISSUE TITLE
RuntimeError: Unsupported architecture WhisperForConditionalGeneration

### ISSUE THREAD

**Issue by Zilai-WANG** [arcee-ai/mergekit#272]
I have the : "RuntimeError: Unsupported architecture WhisperForConditionalGeneration" when I want to use model stock to merge my models. My base model is "base_model: openai/whisper-small.en", which is not supported by the Mergekit right now?

**Comment by cg123** [comment]
That's correct, Whisper models aren't supported by mergekit currently. Support for encoder-decoder models like Whisper has not been implemented yet.
