### ISSUE TITLE
TinyMistral Merged model does generate nothing

### ISSUE THREAD

**Issue by LDelPinoNT** [arcee-ai/mergekit#276]
Hi!

Thank you for creating this amazing tool!
I've been playing with it for a while I tried to merge several local models based on TinyMistral https://huggingface.co/Locutusque/TinyMistral-248M-v2.5 with the "task arithmetic" and "linear" methods but the merged model does generate nothing. 

I'm trying to generate using transformers 4.39.3, but I think that mergekit uses 4.37.1 . Is this version change related? Is there any easy way to upgrade the transformers version? 

Thank you for your time!

**Comment by LDelPinoNT** [comment]
I continued testing and other models also give an empty response for the same test. 
Just forget this issue. Sorry for the waste of time!

**Comment by cg123** [comment]
Closing as it seems you've figured out what was going on, but don't hesitate to reopen if I'm mistaken!

**Comment by Vincent-Li-9701** [comment]
Hi, @LDelPinoNT what was the issue? I also encountered some anomaly. The merged model's performance is really bad.

**Comment by LDelPinoNT** [comment]
Hi @Vincent-Li-9701 the merged model performed as bad as the original model after training without shuffling the dataset. So I can't blame the merging for the bad performance.
