### ISSUE TITLE
How does allow_crimes works

### ISSUE THREAD

**Issue by varunlmxd** [arcee-ai/mergekit#290]
Hey @cg123 can you please mention in doc about allow_crimes and how does it merge model of different architecture.
I tried to merge Llama 3 8B model with Mistral 0.2 7B model 
This is the model repo : https://huggingface.co/varox34/Llama-3-Mistral-v0.2-Instruct-slerp
When I tried to load the model I got this error
ValueError: Trying to set a tensor of shape torch.Size([32000, 4096]) in "weight" (which has shape torch.Size([128256, 4096])), this look incorrect.

**Comment by cg123** [comment]
`--allow-crimes` allows you to attempt to merge models that use different architectures, but does not do anything to fix the problems that can cause. There are only a few specific cases where this is useful. One example is SOLAR, which is actually a Mistral based model wearing a Llama costume - you can successfully merge SOLAR based models with Mistral models that have been expanded in a similar fashion. In general, however, this doesn't work. There are a number of techniques we're investigating to allow general cross-architecture merging but it can't be done yet today.
