### ISSUE TITLE
what is the default model download path ?

### ISSUE THREAD

**Issue by lk1983823** [arcee-ai/mergekit#293]
When I use `mergekit-yaml config.yaml merge --copy-tokenizer --allow-crimes --out-shard-size 1B --lazy-unpickle --trust-remote-code`, it starts to download models from huggingface hub. However, it runs into a stop during the process, and I can't find the parts I have already download. So what is the default path ? Thanks.

**Comment by shamanez** [comment]
It should be in the cache directory.  Now sure.

cd /Users/gayalshamane/.cache/huggingface/hub

**Comment by cg123** [comment]
Yep, by default it'll go in your home directory under `~/.cache/huggingface/hub`.

**Comment by thomasgauthier** [comment]
I would add that to change the default path, one can set the `HF_HOME` environment variable. For instance to download the models on the workspace volume on Runpod.io you can do `HF_HOME="/workspace/.hf" mergekit-yaml path/to/your/config.yml ./output-model-directory`
