### ISSUE TITLE
View size is not compatible with input tensor's size and stride/You are trying to save a non contiguous tensor Fix

### ISSUE THREAD

**Issue by NicolasMejiaPetit** [arcee-ai/mergekit#302]
Tensor_Writer.py has a bug that appears when trying to View size that does not have a compatible with input tensor's size and stride and  Trying to save a non contiguous tensors.

Here is the fix i found to work.

Line 52
` 
   def save_tensor(self, name: str, tensor: torch.Tensor, clone: bool = False):
        tensor_size = tensor.view(-1).shape[0]
        if (
            self.current_shard
            and self.current_shard_size + tensor_size > self.max_shard_size
        ):
            self.flush_current_shard()

        if clone:
            tensor = tensor.clone()

        self.current_shard[name] = tensor
        self.total_size += tensor.numel() * tensor.element_size()
        self.current_shard_size += tensor_size
`
Was fixed when I changed it to
` 
   def save_tensor(self, name: str, tensor: torch.Tensor, clone: bool = False):
        tensor = tensor.contiguous()  # make tensor contiguous before saving
        tensor_size = tensor.view(-1).shape[0]
        if (
            self.current_shard
            and self.current_shard_size + tensor_size > self.max_shard_size
        ):
            self.flush_current_shard()

        if clone:
            tensor = tensor.clone()

        self.current_shard[name] = tensor
        self.current_shard_size += tensor_size
`

Allowing my merges to work.

Also ps @cg123 Could you share the slice config file you used for chargoddard/llama3-42b-v0, i keep getting 

`
ValueError:
                    Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit the
                    quantized model. If you want to dispatch the model on the CPU or the disk while keeping these modules
                    in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom `device_map` to
                    `from_pretrained`. Check
                    https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu
                    for more details.

C:\Users\bobni\OneDrive\Desktop\SeperateExperts\PruneMe\compute_block_similarity>
`
Errors when i try it since i dont have enough vram, or is there a way around this? I'm trying something new out for the arcee competition, and i need to slice a large model, but i get this error when trying to run the computation, its not even attempting to use my shared gpu memory when i set it to cuda, or cpu, it still gives the error.

Actually i edited the script to add change device_map="auto" to ="cuda" and now its using shared memory :)

**Comment by cg123** [comment]
Thanks for the report! This should be fixed in #315.

Here's the config file I used for the 42b model:
```yml
merge_method: passthrough
slices:
  - sources:
      - model: NousResearch/Meta-Llama-3-70B
        layer_range: [0, 41]
  - sources:
      - model: NousResearch/Meta-Llama-3-70B
        layer_range: [73, 80]
dtype: bfloat16
```
