### ISSUE TITLE
Is it supported to merge multiple models into a Mixtral model?

### ISSUE THREAD

**Issue by win10ogod** [arcee-ai/mergekit#32]
Is it supported to merge multiple models into a Mixtral model?

**Comment by cg123** [comment]
It is now! There's a script `mergekit-moe` on the branch `mixtral` now. Keep in mind it's still early and might have problems. There is a little documentation [here](https://github.com/cg123/mergekit/blob/mixtral/moe.md).

**Comment by fakerybakery** [comment]
Thank you so much for making this project! It keeps on getting better!

**Comment by fakerybakery** [comment]
Thank you so much! Might it be possible to merge this into the main branch?

**Comment by fakerybakery** [comment]
Hi @cg123, also, would you mind providing an example for the YAML config file?

**Comment by ddh0** [comment]
@fakerybakery here is an example config.yml from Undi: https://huggingface.co/Undi95/Mixtral-8x7B-MoE-RP-Story/blob/main/config.yaml

**Comment by fakerybakery** [comment]
Thanks!
