### ISSUE TITLE
RuntimeError: Unsupported architecture Qwen2ForSequenceClassification

### ISSUE THREAD

**Issue by iseesaw** [arcee-ai/mergekit#369]

**Comment by lrsbrgrn** [comment]
Hi @iseesaw, any news regarding your issue?

I'm currently facing the same behavior -> `RuntimeError: Unsupported architecture BertForSequenceClassification`

Thx!

**Comment by iseesaw** [comment]
> Hi @iseesaw, any news regarding your issue?
> 
> I'm currently facing the same behavior -> `RuntimeError: Unsupported architecture BertForSequenceClassification`
> 
> Thx!

You can just modify the architecture data.
![Xnip2024-07-25_18-01-15](https://github.com/user-attachments/assets/6a4d2c03-017d-495d-9745-952cebc46860)

**Comment by lrsbrgrn** [comment]
`BertForTokenClassification` seems to be already supported as you can see in [mergekit/_data/architectures/bert-sequence-classification.json](https://github.com/arcee-ai/mergekit/blob/main/mergekit/_data/architectures/bert-sequence-classification.json)

```
"architectures": [
        "BertForSequenceClassification",
        "BertForMultipleChoice",
        "BertForTokenClassification"
    ]
```
