### ISSUE TITLE
Error at MoE Qwen 1.5B

### ISSUE THREAD

**Issue by ehristoforu** [arcee-ai/mergekit#395]
```
mergekit-moe config.yaml merge --copy-tokenizer --device cuda --low-cpu-memory --trust-remote-code
ERROR:root:No output architecture found that is compatible with the given models.
ERROR:root:All supported output architectures:
ERROR:root:  * Mixtral
ERROR:root:  * DeepSeek MoE
ERROR:root:  * Qwen MoE
```

I have the latest version of mergekit, I use only Qwen2 models and only 1.5B weight, no custom code.

**Comment by ZhangJiayuan-BUAA** [comment]
The same question

**Comment by ZhangJiayuan-BUAA** [comment]
Qwen models must specify onr shared expert. I hope this will solve your problem.

mergekit/moe/qwen.py
![image](https://github.com/user-attachments/assets/d3d372f2-4a31-4a9c-a719-11ccbca0cc36)

**Comment by ehristoforu** [comment]
Sorry, I didn't quite understand the meaning of the words "one common" expert

Here is my config:
```
MODEL_NAME = "newmoe-0"
yaml_config = """
base_model: ehristoforu/Qwen2-1.5b-it-chat
gate_mode: hidden
dtype: bfloat16
experts:
- source_model: ehristoforu/Qwen2-1.5b-it-chat
positive_prompts: ["chat", "assistant", "chat history", "chat context", "writing", "text writing", "editing", "text editing", "multilingual"]
- source_model: ehristoforu/Qwen2-1.5b-it-bioinstruct
positive_prompts: ["bio", "science", "biology", "natural sciences", "scientist"]
- source_model: ehristoforu/Qwen2-1.5b-it-codealpaca
positive_prompts: ["code", "coding", "coder", "programming", "programmer", "code analysis", "code review", "code fix", "code improvement"]
- source_model: ehristoforu/Qwen2-1.5b-it-math
positive_prompts: ["math", "mathematician", "problem solving", "calculating", "logics"]
```

All models in fp16, in PyTorch (.bin) format, pre-trained Qwen2 1.5B without merging.

What exactly do I need to change?

**Comment by lijinfeng0713** [comment]
> > Qwen models must specify one shared expert. I hope this will solve your problem.
> > mergekit/moe/qwen.py ![image](https://private-user-images.githubusercontent.com/58897524/357398428-d46cff6b-e39a-4204-aaff-bc3c43bbd054.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1ODI4NTksIm5iZiI6MTcyMzU4MjU1OSwicGF0aCI6Ii81ODg5NzUyNC8zNTczOTg0MjgtZDQ2Y2ZmNmItZTM5YS00MjA0LWFhZmYtYmMzYzQzYmJkMDU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDIwNTU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwNDhkN2QzOTAzZThiNGNkMDFmMTUzZmU0YjA3YzczMDAxODhmMTVlNDJlMTBhYmU5ZDdjMmJlNTFjZDgwOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eBNY4wW61hXu0on7vST5H2T1i_JigOnGbrzmgjJOS14)
> 
> Sorry, I didn't quite understand the meaning of the words "one shared" expert
> 
> Here is my config:
> 
> ```
> MODEL_NAME = "newmoe-0"
> yaml_config = """
> base_model: ehristoforu/Qwen2-1.5b-it-chat
> gate_mode: hidden
> dtype: bfloat16
> experts:
> - source_model: ehristoforu/Qwen2-1.5b-it-chat
> positive_prompts: ["chat", "assistant", "chat history", "chat context", "writing", "text writing", "editing", "text editing", "multilingual"]
> - source_model: ehristoforu/Qwen2-1.5b-it-bioinstruct
> positive_prompts: ["bio", "science", "biology", "natural sciences", "scientist"]
> - source_model: ehristoforu/Qwen2-1.5b-it-codealpaca
> positive_prompts: ["code", "coding", "coder", "programming", "programmer", "code analysis", "code review", "code fix", "code improvement"]
> - source_model: ehristoforu/Qwen2-1.5b-it-math
> positive_prompts: ["math", "mathematician", "problem solving", "calculating", "logics"]
> ```
> 
> All models in fp16, in PyTorch (.bin) format, pre-trained Qwen2 1.5B without merging.
> 
> What exactly do I need to change?

Have you solved your problem? I have the same error when merging qwen2-0.5b
