### ISSUE TITLE
How to Load Models Downloaded from Hugging Face in a Script?

### ISSUE THREAD

**Issue by hywchina** [arcee-ai/mergekit#40]
Thank you very much for your open-source project, it has been immensely helpful to me. I've encountered an issue during use and am hoping to get your assistance.

I have downloaded several models from Hugging Face to my personal directory at `~/.cache/huggingface/hub`. I'm wondering how to read these models directly in my script. Could you please guide me on how to achieve this? 

Looking forward to your response. Thank you!

**Comment by cg123** [comment]
I'm glad it has been helpful!

If I'm interpreting you right then you shouldn't need to do anything special - by default mergekit fetches models from huggingface and uses their caching, so I think you should be able to just refer to them by `hf_user/model_name` as usual.

If you want to explicitly refer to the files on disk then you can use an absolute or relative path instead. The only catch is that `~` doesn't get substituted, so you'll need to write `/home/your_username` (or the equivalent for your OS) instead. If for whatever reason you want to explicitly refer to a model in your Hugging Face cache then you can point it to a specific snapshot folder. For example, here's how I would refer to my local copy of Llama-2 13B:
```
base_model: /home/goddard/.cache/huggingface/hub/models--TheBloke--Llama-2-13B-fp16/snapshots/b2e65e8ad4bb35e5abaee0170ebd5fc2134a50bb
```

**Comment by sviknesh97** [comment]
Hey @cg123 kudos really good work done, I have some questions

If we merge the 2 models 
![20240109_134453](https://github.com/cg123/mergekit/assets/100233528/c47161fb-ac1f-49b3-bae4-f9330d4b917e)

We get a dir such as this, so I was wondering if we can use this modek without pushing to hugging face

**Comment by cg123** [comment]
Absolutely - you can load it in the same way you would a model on the hub if you use the full path of the output folder.
