### ISSUE TITLE
Support for GPTBigCodeForCausalLM (StarCoder)

### ISSUE THREAD

**Issue by rpand002** [arcee-ai/mergekit#80]
Could you please extend the functions to use with [bigcode](https://huggingface.co/bigcode)/[starcoder](https://huggingface.co/bigcode/starcoder) [GPTBigCodeForCausalLM Architecture]. This would be great for the BigCode community in merging different code LLMs. Thanks!

@cg123

**Comment by cg123** [comment]
I've added initial support on a branch (see #83) - if you have a chance to give it a shot and let me know if it works for your needs I'd appreciate it.
